### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by hmh0816** [TakHemlata/RawBoost-antispoofing#2]
Hi, i have problems with version  ,look forward to your reply
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import torch
  File "/home/sr617/miniconda3/envs/RawBoost_antispoofing/lib/python3.8/site-packages/torch/__init__.py", line 192, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/sr617/miniconda3/envs/RawBoost_antispoofing/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so: undefined symbol: cudaGraphRetainUserObject, version libcudart.so.11.0

**Comment by TakHemlata** [comment]
Hello,

I think you have to download latest PyTorch version to run the code.

Thanks
